services:
 nimbly:
    build: ./docker-nimbly
    container_name: nimbly
    volumes:
      - ..:/var/www/nimbly
    ports:
      - 80:80
 nimbly-openshift:
    build: 
      context: ../
      dockerfile: ./docker/docker-nimbly-openshift/Dockerfile
    container_name: nimbly_openshift
    ports:
      - 8080:8080
